const facilities = [
  "ActiveSG Gym at Ang Mo Kio CC\n\n795, ANG MO KIO COMMUNITY CENTRE, ANG MO KIO AVENUE 1,",
  "ActiveSG Gym at Fernvale Square\n\n51A, SENGKANG WEST AVENUE,",
  "ActiveSG Gym at Toa Payoh West CC\n\n200, TOA PAYOH WEST COMMUNITY CLUB, LORONG 2 TOA PAYOH,",
  "ActiveSG Hockey Village Gym @ Boon Lay\n\n88, BOON LAY PLACE,",
  "Admiralty Primary School Field",
  "Admiralty Primary School Hall\n\n11, ADMIRALTY PRIMARY SCHOOL, WOODLANDS CIRCLE,",
  "Ahmad Ibrahim Primary School Hall\n\n10, AHMAD IBRAHIM PRIMARY SCHOOL, YISHUN STREET 11,",
  "Ai Tong School Field",
  "Anchor Green Primary School Hall\n\n31 Anchorvale Drive",
  "Anderson Secondary School Field\n\n10 Ang Mo Kio Street 53",
  "Anderson Secondary School Hall\n\n10 Ang Mo Kio Street 53",
  "Ang Mo Kio Primary School Field\n\n20 Ang Mo Kio Avenue 3",
  "Ang Mo Kio Secondary School Field\n\n6 Ang Mo Kio Street 22",
  "Ang Mo Kio Secondary School Hall\n\n6 Ang Mo Kio Street 22",
  "Ang Mo Kio Swimming Complex\n\n1771 Ang Mo Kio Avenue 1",
  "Bartley Secondary School Field\n\n10 Jalan Bunga Rampai",
  "Bartley Secondary School Hall\n\n10, BARTLEY SECONDARY SCHOOL, JALAN BUNGA RAMPAI,",
  "Beacon Primary School Hall\n\n36, BEACON PRIMARY SCHOOL, BUKIT PANJANG RING ROAD,",
  "Beatty Secondary School Field\n\n1 Toa Payoh North",
  "Beatty Secondary School Hall\n\n1 Toa Payoh North",
  "Bedok Green Primary School Field\n\n1 Bedok South Avenue 2",
  "Bedok Green Primary School Hall\n\n1, BEDOK GREEN PRIMARY SCHOOL, BEDOK SOUTH AVENUE 2,",
  "Bedok Green Secondary School Field\n\n360 Bedok North Avenue 3",
  "Bedok North Secondary School Field\n\n20 Jalan Damai",
  "Bedok North Secondary School Hall\n\n20 Jalan Damai",
  "Bedok South Secondary School Field\n\n1 Jalan Langgar Bedok",
  "Bedok South Secondary School Hall\n\n1 Jalan Langgar Bedok",
  "Bedok Sport Centre\n\n11, HEARTBEAT @ BEDOK, BEDOK NORTH STREET 1,",
  "Bedok Sport Hall\n\n3 Bedok North Street 2",
  "Bedok Stadium\n\n1 Bedok North Street 2",
  "Bedok Tennis Centre\n\n3 Bedok North Street 2",
  "Bedok View Secondary School Field\n\n6 Bedok South Avenue 3,",
  "Bedok View Secondary School Hall\n\n6 Bedok South Avenue 3,",
  "Bendemeer Primary School Field\n\n91 Bendemeer Road",
  "Bendemeer Secondary School Field\n\n1 St. Wilfred Road",
  "Bendemeer Secondary School Hall\n\n1 St. Wilfred Road",
  "Bishan ActiveSG Gym\n\n5 Bishan Street 14",
  "Bishan Park Secondary School Field\n\n2 Sin Ming Walk",
  "Bishan Sport Centre\n\n5 Bishan St 14",
  "Bishan Sports Hall\n\n5 Bishan Street 14",
  "Bishan Stadium\n\n7 Bishan Street 14",
  "Bishan Swimming Complex\n\n1 Bishan Street 14",
  "Blangah Rise Primary School Field\n\n91 Telok Blangah Heights",
  "Blangah Rise Primary School Hall\n\n91, BLANGAH RISE PRIMARY SCHOOL, TELOK BLANGAH HEIGHTS,",
  "Boon Lay Secondary School Field\n\n11 Jurong West Street 65",
  "Bowen Secondary School Field\n\n2 Lorong Napiri",
  "Broadrick Secondary School Field\n\n61 Dakota Crescent",
  "Bukit Batok ActiveSG Gym\n\n2, BUKIT BATOK SWIMMING COMPLEX, BUKIT BATOK STREET 22,",
  "Bukit Batok Swimming Complex\n\n2 Bukit Batok Street 22",
  "Bukit Gombak ActiveSG Gym\n\n810 Bukit Batok West Avenue 5",
  "Bukit Gombak Sport Centre\n\n810 Bukit Gombak West Ave 5",
  "Bukit Gombak Sports Hall\n\n810 Bukit Batok West Avenue 5",
  "Bukit Gombak Stadium\n\n800 Bukit Batok West Avenue 5",
  "Bukit View Secondary School Field\n\n16 Bukit Batok Street 21",
  "Bukit View Secondary School Hall\n\n16 Bukit Batok Street 21",
  "Burghley Squash Centre\n\n43 Burghley Drive",
  "Burghley Tennis Centre\n\n43 Burghley Drive",
  "Canberra Primary School Field\n\n21 Admiralty Drive",
  "Canberra Secondary School Field\n\n51 Sembawang Drive",
  "Cantonment Primary School Field\n\n1 Cantonment Close Singapore 088256",
  "Casuarina Primary School Field\n\n30 Pasir Ris Street 41",
  "Cedar Primary School Field\n\n15 Cedar Ave, Singapore 349700",
  "Cedar Primary School Hall\n\n15, CEDAR PRIMARY SCHOOL, CEDAR AVENUE,",
  "Changkat Changi Secondary School Field\n\n23 Simei Street 3",
  "Changkat Changi Secondary School Hall\n\n23, CHANGKAT CHANGI SECONDARY SCHOOL, SIMEI STREET 3,",
  "Changkat Primary School Hall\n\n11, CHANGKAT PRIMARY SCHOOL, SIMEI STREET 3,",
  "CHIJ Katong Primary School Hall\n\n17, CHIJ (KATONG) PRIMARY, MARTIA ROAD,",
  "CHIJ St Theresa Convent School Hall\n\n160, CHIJ ST. THERESAS CONVENT, LOWER DELTA ROAD,",
  "CHIJ St. Joseph's Convent School Hall\n\n62, CHIJ ST. JOSEPH CONVENT SCHOOL, SENGKANG EAST WAY,",
  "Choa Chu Kang ActiveSG Gym Level 3 (Free weights)\n\n1 Choa Chu Kang Street 53",
  "Choa Chu Kang Secondary School Field\n\n3 Teck Whye Crescent",
  "Choa Chu Kang Sport Centre\n\n1 Choa Chu Kang St 53",
  "Choa Chu Kang Sports Hall\n\n1 Choa Chu Kang Street 53",
  "Choa Chu Kang Stadium\n\n1 Choa Chu Kang Street 53",
  "Choa Chu Kang Street Soccer Court\n\n1 Choa Chu Kang Street 53",
  "Choa Chu Kang Swimming Complex\n\n1 Choa Chu Kang Street 53",
  "Choa Chu Kang Tennis Centre\n\n1 Choa Chu Kang Street 53",
  "Chongfu School Hall\n\n170, CHONGFU PRIMARY SCHOOL, YISHUN AVENUE 6,",
  "Christ Church Secondary School Hall\n\n20, CHRIST CHURCH SECONDARY SCHOOL, WOODLANDS DRIVE 17,",
  "Chung Cheng High School Hall (Main)\n\n50, CHUNG CHENG HIGH SCHOOL (MAIN), GOODMAN ROAD,",
  "Chung Cheng High School Hall (Yishun)\n\n11, CHUNG CHENG HIGH SCHOOL (YISHUN), YISHUN STREET 61,",
  "Clementi ActiveSG Gym\n\n518 Clementi Avenue 3",
  "Clementi Primary School Hall\n\n8 Clementi Avenue 3",
  "Clementi Sport Centre\n\n518 Clementi Ave 3",
  "Clementi Sports Hall\n\n518 Clementi Avenue 3",
  "Clementi Stadium\n\n10, West Coast Walk",
  "Clementi Swimming Complex\n\n520 Clementi Avenue 3",
  "Clementi Town Secondary School Field\n\n10 Clementi Avenue 3",
  "Clementi Town Secondary School Hall\n\n10 Clementi Avenue 3",
  "Clementi Woods Secondary School Field\n\n170 West Coast Road",
  "Commonwealth Secondary School Field\n\n698 West Coast Road",
  "Commonwealth Secondary School Hall\n\n698 West Coast Road",
  "Compassvale Primary School Hall\n\n21, COMPASSVALE PRIMARY SCHOOL, COMPASSVALE STREET,",
  "Compassvale Secondary School Field\n\n51 Compassvale Crescent",
  "Corporation Primary School Field\n\n31 Jurong West Street 24",
  "Corporation Primary School Hall\n\n31, CORPORATION PRIMARY SCHOOL, JURONG WEST STREET 24,",
  "Crescent Girls School Field\n\n357 Tanglin Road",
  "Crescent Girls Secondary School Hall\n\n357 Tanglin Road",
  "Crest Secondary School Field\n\n561 Jurong East Street 24",
  "Crest Secondary School Hall\n\n561 Jurong East Street 24\nSingapore 609561",
  "Crest Secondary School Outdoor Basketball Court\n\n561 Jurong East Street 24",
  "Crest Secondary School Street Soccer Court\n\n561 Jurong East Street 24",
  "Damai Secondary School Field\n\n4800 Bedok Reservoir Road",
  "Dazhong Primary School Field",
  "Dazhong Primary School Hall\n\n35, DAZHONG PRIMARY SCHOOL, BUKIT BATOK STREET 31,",
  "Delta ActiveSG Gym\n\n900 Tiong Bahru Road",
  "Delta Dance Studio\n\n900 Tiong Bahru Road",
  "Delta Hockey Pitch\n\n900 Tiong Bahru Road",
  "Delta Sport Centre\n\n900 Tiong Bahru Road",
  "Delta Sports Hall\n\n900 Tiong Bahru Road",
  "Delta Swimming Complex\n\n900 Tiong Bahru Road",
  "Deyi Secondary School Field\n\n1 Ang Mo Kio Street 42",
  "Deyi Secondary School Hall\n\n1, DEYI SECONDARY SCHOOL, ANG MO KIO STREET 42,",
  "Dunearn Secondary School Field\n\n21 Bukit Batok West Avenue 2,",
  "Dunearn Secondary School Hall\n\n21, DUNEARN SECONDARY SCHOOL, BUKIT BATOK WEST AVENUE 2,",
  "Dunman High School Hall\n\n10 Tanjong Rhu Rd",
  "Dunman Secondary School Field\n\n21, DUNMAN SECONDARY SCHOOL, TAMPINES STREET 45,",
  "East Spring Primary School Field\n\n31 Tampines Street 33",
  "East Spring Secondary School Field\n\n30 Tampines Street 34",
  "East Spring Secondary School Hall\n\n30 Tampines Street 34",
  "Edgefield Primary School Hall\n\n41, EDGEFIELD PRIMARY SCHOOL, EDGEFIELD PLAINS,",
  "Edgefield Secondary School Hall\n\n36 Punggol Field",
  "Elias Park Primary School Field\n\n11 Pasir Ris Street 52",
  "Elias Park Primary School Hall\n\n11, ELIAS PARK PRIMARY SCHOOL, PASIR RIS STREET 52,",
  "Enabling Village ActiveSG Gym\n\n20, Lengkok Bahru, #01-05, Enabling Village",
  "Endeavour Primary School Field\n\n10 Admiralty Link",
  "Endeavour Primary School Field\n\n10 Admiralty Link",
  "Eunoia Junior College Field - Frisbee only\n\n2, EUNOIA JUNIOR COLLEGE, SIN MING PLACE,",
  "Eunos Primary School Field\n\n95 Jalan Eunos",
  "Evergreen Primary School Field\n\n31 WOODLANDS CIRCLE Singapore 738908",
  "Evergreen Primary School Hall\n\n31, EVERGREEN PRIMARY SCHOOL, WOODLANDS CIRCLE,",
  "Evergreen Secondary School Field\n\n11 Woodlands Street 83",
  "Evergreen Secondary School Hall\n\n11, EVERGREEN SECONDARY SCHOOL, WOODLANDS STREET 83,",
  "Fairfield Methodist Primary School Hall\n\n100, FAIRFIELD METHODIST PRIMARY SCHOOL, DOVER ROAD,",
  "Fairfield Methodist Secondary School Hall\n\n102, FAIRFIELD METHODIST SECONDARY SCHOOL, DOVER ROAD,",
  "Fajar Secondary School Basketball Court\n\n31 Gangsa Road Singapore 678972",
  "Fajar Secondary School Field\n\n31 Gangsa Road Singapore 678972",
  "Fajar Secondary School Field\n\n31 GANGSA ROAD",
  "Fajar Secondary School Hall\n\n31 GANGSA ROAD",
  "Farrer Park Field\n\n3 Rutland Road",
  "Farrer Park Tennis Centre\n\n1 Rutland Road",
  "Fengshan Primary School Field\n\n307 BEDOK NORTH ROAD Singapore 469680",
  "Fengshan Primary School Hall\n\n307, FENGSHAN PRIMARY SCHOOL, BEDOK NORTH ROAD,",
  "Fern Green Primary School Hall\n\n70, FERNVALE LINK,",
  "First Toa Payoh Primary School Hall\n\n7, FIRST TOA PAYOH PRIMARY SCHOOL, LORONG 8 TOA PAYOH,",
  "First Toa Payoh Secondary School Field\n\n580 Toa Payoh East",
  "Former Chestnut Drive Secondary School Field\n\n58 Chestnut Drive",
  "Former Shuqun Secondary School Field\n\n450 Jurong East Street 21",
  "Former Shuqun Secondary School Hall\n\n450 Jurong East Street 21",
  "Frontier Primary School Field\n\n20 Jurong West Street 61, Singapore 648200",
  "Frontier Primary School Hall\n\n20 Jurong West Street 61",
  "Fuchun Secondary School Field\n\n21 Woodlands Avenue 1",
  "Fuhua Secondary School Field\n\n5 Jurong West Street 41",
  "Fuhua Secondary School Hall\n\n5 Jurong West Street 41",
  "Gan Eng Seng Primary School Field\n\n100 REDHILL CLOSE Singapore 158901",
  "Gan Eng Seng Secondary School Hall\n\n1 Henderson Road",
  "Geylang East Dance Studio\n\nGeylang East Dance Studio",
  "Geylang East Swimming Complex\n\n601 Aljunied Avenue 1",
  "Geylang Field\n\n30 Lorong 12 Geylang",
  "Gongshang Primary School Hall A (Level 3)\n\n1, GONGSHANG PRIMARY SCHOOL, TAMPINES STREET 42,",
  "Gongshang Primary School Hall B (Level 1)\n\n1, GONGSHANG PRIMARY SCHOOL, TAMPINES STREET 42,",
  "Greendale Primary School Hall\n\n50 Edgedale Plains",
  "Greendale Secondary School Field\n\n51 Edgedale Plains",
  "Greenridge Primary School Field",
  "Greenridge Secondary School Field\n\n32 Bukit Panjang Ring Road",
  "Greenridge Secondary School Hall\n\n32 Bukit Panjang Ring Road",
  "Greenview Secondary School Field\n\n15 Pasir Ris Street 21",
  "Greenwood Primary School Field\n\n11 Woodlands Drive 62 Singapore 737942",
  "Hai Sing Catholic School Field\n\n9 Pasir Ris Drive 6",
  "Haig Girls' Primary School Field",
  "Heartbeat @ Bedok ActiveSG Gym\n\n11, BEDOK NORTH STREET 1,",
  "Heartbeat @ Bedok ActiveSG Sport Centre\n\n11, BEDOK NORTH STREET 1,",
  "Heartbeat @ Bedok ActiveSG Sports Hall\n\n11, BEDOK NORTH STREET 1,",
  "Heartbeat @ Bedok ActiveSG Swimming Complex\n\n11, BEDOK NORTH STREET 1,",
  "Heartbeat @ Bedok ActiveSG Tennis Centre\n\n11, BEDOK NORTH STREET 1,",
  "Heartbeat @ Bedok Table Tennis Area\n\n11, HEARTBEAT @ BEDOK, BEDOK NORTH STREET 1,",
  "Henderson Secondary School Field\n\n100 Henderson Road",
  "Hockey Village Multi-Purpose Pitch @ Boon Lay\n\n88 BOON LAY PLACE",
  "Home of Athletics\n\n52 Stadium Road",
  "Hougang ActiveSG Gym\n\n93 Hougang Ave 4\n#02-05",
  "Hougang Primary School Hall\n\n1 Hougang Street 93",
  "Hougang Sport Centre\n\n93 Hougang Ave 4",
  "Hougang Sports Hall\n\n93 Hougang Avenue 4",
  "Hougang Stadium\n\n100 Hougang Avenue 2",
  "Hougang Swimming Complex\n\n95 Hougang Avenue 4",
  "Hua Yi Secondary School Field\n\n60 Jurong West Street 42",
  "Hua Yi Secondary School Hall\n\n60 Jurong West Street 42",
  "Huamin Primary School Field\n\n530 Yishun Ring Road",
  "Innova Primary School Field",
  "Innova Primary School Hall\n\n80 Woodlands Drive 17",
  "Jalan Besar ActiveSG Gym\n\n100, JALAN BESAR STADIUM, TYRWHITT ROAD,",
  "Jalan Besar Sport Centre\n\n100 Tyrwhitt Road",
  "Jalan Besar Stadium\n\n100 Tyrwhitt Road",
  "Jalan Besar Swimming Complex\n\n100 Tyrwhitt Road",
  "Jiemin Primary School Hall\n\n2, JIEMIN PRIMARY SCHOOL, YISHUN STREET 71,",
  "Junyuan Primary School Hall\n\n2, Tampines Street 91",
  "Junyuan Secondary School Field\n\n11 Tampines Street 84",
  "Jurong East ActiveSG Gym\n\n21 Jurong East Street 31",
  "Jurong East Gateball Court\n\n21 Jurong East Street 31",
  "Jurong East Petanque Courts\n\n21 Jurong East Street 31",
  "Jurong East Sport Centre\n\n21 Jurong East St 31",
  "Jurong East Sport Hall\n\n21 Jurong East Street 31",
  "Jurong East Stadium\n\n21 Jurong East Street 31",
  "Jurong East Swimming Complex\n\n21 Jurong East Street 31",
  "Jurong Lake Gardens Gym\n\n30 Yuan Ching Road, Singapore 618664",
  "Jurong Lake Gardens Pool\n\n30 Yuan Ching Road, Singapore 618664",
  "Jurong Primary School Hall\n\n320, JURONG PRIMARY SCHOOL, JURONG EAST STREET 32,",
  "Jurong Secondary School Hall\n\n31 Yuan Ching Road",
  "Jurong West ActiveSG Gym\n\n20 Jurong West Street 93",
  "Jurong West Primary School Hall\n\n30, JURONG WEST PRIMARY SCHOOL, JURONG WEST STREET 61,",
  "Jurong West Secondary School Field\n\n61 Jurong West Street 65",
  "Jurong West Secondary School Hall\n\n61 Jurong West Street 65",
  "Jurong West Sport Centre\n\n20 Jurong West St 93",
  "Jurong West Sports Hall\n\n20 Jurong West Street 93",
  "Jurong West Stadium\n\n20 Jurong West Street 93",
  "Jurong West Swimming Complex\n\n20 Jurong West Street 93",
  "Jurong West Tennis Centre\n\n20 Jurong West Street 93",
  "Jurongville Secondary School Hall\n\n202 Jurong East Ave 1",
  "Juying Primary School Hall\n\n31, JUYING PRIMARY SCHOOL, JURONG WEST STREET 91,",
  "Juying Secondary School Field\n\n33 Jurong West Street 91",
  "Kallang Basin ActiveSG Gym\n\n21, KALLANG BASIN SWIMMING COMPLEX, GEYLANG BAHRU LANE,",
  "Kallang Basin Swimming Complex\n\n23 Geylang Bahru Lane",
  "Kallang Field\n\n31, STADIUM CRESCENT,",
  "Kallang Lawn Bowl\n\n8 Stadium Boulevard",
  "Kallang Netball Centre\n\n6 Stadium Boulevard",
  "Kallang Sport Centre\n\n52 Stadium Road",
  "Kallang Squash Centre\n\n8 Stadium Boulevard",
  "Kallang Tennis Centre\n\n8 Stadium Boulevard",
  "Katong Swimming Complex\n\n111 Wilkinson Road",
  "Keming Primary School Field\n\n90 Bukit Batok East Avenue 6",
  "Keming Primary School Hall\n\n90, KEMING PRIMARY SCHOOL, BUKIT BATOK EAST AVENUE 6,",
  "Kent Ridge Secondary School Field\n\n147 West Coast Road",
  "Kent Ridge Secondary School Hall\n\n147 West Coast Road",
  "Kranji Primary School Hall\n\n11, KRANJI PRIMARY SCHOOL, CHOA CHU KANG STREET 54,",
  "Kranji Secondary School Field\n\n61 Choa Chu Kang Street 51",
  "Kranji Secondary School Hall\n\n61, KRANJI SECONDARY SCHOOL, CHOA CHU KANG STREET 51,",
  "Kuo Chuan Presbyterian Primary School Hall\n\n8, KUO CHUAN PRESBYTERIAN PRIMARY SCHOOL, BISHAN STREET 13,",
  "Kuo Chuan Presbyterian Secondary School Hall\n\n10, KUO CHUAN PRESBYTERIAN SECONDARY SCHOOL, BISHAN STREET 13,",
  "Lakeside Primary School Field\n\n161 Corporation Walk",
  "Lianhua Primary School Field",
  "Macpherson Secondary School Field\n\n121 Circuit Road",
  "Marsiling Primary School Hall\n\n31, MARSILING PRIMARY SCHOOL, WOODLANDS CENTRE ROAD,",
  "Marsiling Secondary School Field\n\n12 Marsiling Road",
  "Mayflower Secondary School Field\n\n2 Ang Mo Kio Street 21",
  "Mee Toh School Field\n\n21 Edgedale Plains",
  "Meridian Primary School Field\n\n20 Pasir Ris Street 71",
  "Meridian Secondary School Field\n\n31 Pasir Ris Street 51",
  "Meridian Secondary School Hall\n\n31 Pasir Ris Street 51",
  "Methodist Girls' School Hall (Primary)\n\n11, METHODIST GIRLS SCHOOL (PRIMARY), BLACKMORE DRIVE,",
  "MOE (Evans) Stadium\n\n21 Evans Road",
  "MOE Evans Hockey Pitch\n\n21 Evans Road",
  "Nan Chiau High School Field\n\n20 Anchorvale Link",
  "Nan Chiau High School Hall\n\n20, NAN CHIAU HIGH SCHOOL, ANCHORVALE LINK,",
  "Nan Chiau Primary School Hall\n\n50, NAN CHIAU PRIMARY SCHOOL, ANCHORVALE LINK,",
  "Nan Hua High School Field\n\n41 Clementi Avenue 1",
  "Nan Hua High School Hall\n\n41 Clementi Avenue 1",
  "Nanyang Primary School Hall\n\n27, KING'S ROAD,",
  "Naval Base Secondary School Field\n\n901 Yishun Ring Road",
  "Naval Base Secondary School Hall\n\n901 Yishun Ring Road",
  "New Town Primary School Field\n\n300 Tanglin Halt Road",
  "Ngee Ann Secondary School Field\n\n1, NGEE ANN SECONDARY SCHOOL, TAMPINES STREET 32,",
  "Ngee Ann Secondary School Hall\n\n1, NGEE ANN SECONDARY SCHOOL, TAMPINES STREET 32,",
  "North Spring Primary School Hall\n\n1, NORTH SPRING PRIMARY SCHOOL, RIVERVALE STREET,",
  "North View Primary School Field\n\n210 Yishun Avenue 6",
  "North Vista Primary School Hall\n\n20, NORTH VISTA PRIMARY SCHOOL, COMPASSVALE LINK,",
  "North Vista Secondary School Field\n\n11 Rivervale Link",
  "North Vista Secondary School Hall\n\n11 Rivervale Link",
  "Northbrooks Secondary School Field\n\n585 Yishun Ring Road",
  "Northland Primary School Field\n\n15 Yishun Avenue 4",
  "Northland Secondary School Hall\n\n3 Yishun Street 22",
  "NUS University Town, Stephen Riady Centre, Hall 1\n\n2, COLLEGE AVENUE WEST,",
  "Oasis Primary School Field\n\n71 Edgefield Plains",
  "Orchid Park Secondary School Field\n\n10 Yishun Street 81",
  "Our Tampines Hub - Community Auditorium\n\n1, OUR TAMPINES HUB, TAMPINES WALK,",
  "Our Tampines Hub - Team Sports Hall\n\n1, OUR TAMPINES HUB, TAMPINES WALK,",
  "Palm View Primary School Hall\n\n150 Compassvale Bow",
  "Park View Primary School Field\n\n60 Pasir Ris Drive 1",
  "Park View Primary School Hall\n\n60, PARK VIEW PRIMARY SCHOOL, PASIR RIS DRIVE 1,",
  "Pasir Ris 5 a Side Soccer\n\n120 Pasir Ris Central",
  "Pasir Ris ActiveSG Gym\n\n120 Pasir Ris Central",
  "Pasir Ris Crest Secondary School Field\n\n11 Pasir Ris Street 41",
  "Pasir Ris Crest Secondary School Hall\n\n11 Pasir Ris Street 41",
  "Pasir Ris Primary School Field\n\n5 Pasir Ris Street 21",
  "Pasir Ris Primary School Hall\n\n5, PASIR RIS PRIMARY SCHOOL, PASIR RIS STREET 21,",
  "Pasir Ris Secondary School Field\n\n390 Tampines Street 21",
  "Pasir Ris Secondary School Hall\n\n390 Tampines Street 21",
  "Pasir Ris Sport Centre\n\n120 Pasir Ris Central",
  "Pasir Ris Sports Hall\n\n120 Pasir Ris Central",
  "Pasir Ris Swimming Complex\n\n120 Pasir Ris Central",
  "Pasir Ris Tennis Centre\n\n120 Pasir Ris Central",
  "Pei Hwa Secondary School Field\n\n21 Fernvale Link",
  "Pei Hwa Secondary School Hall\n\n21, PEI HWA SECONDARY SCHOOL, FERNVALE LINK,",
  "Peicai Secondary School Hall\n\n10 Serangoon Avenue 4",
  "Peirce Secondary School Field\n\n10 Sin Ming Walk",
  "Pierce Secondary School Hall\n\n10 Sin Ming Walk",
  "Ping Yi Secondary School Field\n\n61 Chai Chee Street",
  "Ping Yi Secondary School Hall\n\n61 Chai Chee Street",
  "Pioneer Primary School Field",
  "Pioneer Secondary School Field\n\n21 Jurong West Street 81",
  "Poi Ching School Hall\n\n21 Tampines Street 71",
  "Punggol Cove Primary School Field\n\n52 Sumang Walk",
  "Punggol Cove Primary School Hall\n\n52, PUNGGOL COVE PRIMARY SCHOOL, SUMANG WALK,",
  "Punggol Green Primary School Field\n\n98 Punggol Walk",
  "Punggol Green Primary School Hall\n\n98, PUNGGOL GREEN PRIMARY SCHOOL, PUNGGOL WALK,",
  "Punggol Primary School Field\n\n61 Hougang Avenue 8",
  "Punggol Secondary School Field\n\n51 Edgefield Plains",
  "Punggol Secondary School Hall\n\n51 Edgefield Plains",
  "Qifa Primary School Field",
  "Qifa Primary School Hall\n\n50, QIFA PRIMARY SCHOOL, WEST COAST AVENUE,",
  "Queenstown Secondary School Field\n\n1 Strathmore Road",
  "Queenstown Secondary School Hall\n\n1 Strathmore Road",
  "Queenstown Sport Centre\n\n473 Stirling Road",
  "Queenstown Stadium\n\n473A Stirling Road",
  "Queenstown Swimming Complex\n\n473 Stirling Road",
  "Queensway Secondary School Field\n\n2A Margaret Drive",
  "Queensway Secondary School Hall\n\n2A Margaret Drive",
  "Radin Mas Primary School Field\n\n1 Bukit Purmei Avenue",
  "Radin Mas Primary School Hall\n\n1 Bukit Purmei Avenue",
  "Raffles Girls' Primary School Field\n\n21 Hillcrest Road",
  "Regent Secondary School Field\n\n50 Choa Chu Kang North 5",
  "Regent Secondary School Hall\n\n50, REGENT SECONDARY SCHOOL, CHOA CHU KANG NORTH 5,",
  "Riverside Secondary School Field\n\n3 Woodlands Street 81",
  "Riverside Secondary School Hall\n\n3 Woodlands Street 81",
  "Rivervale Primary School Hall\n\n80, RIVERVALE PRIMARY SCHOOL, RIVERVALE DRIVE,",
  "Rosyth Primary School Field\n\n21 Serangoon North Avenue 4",
  "Rulang Primary School Hall\n\n6, RULANG PRIMARY SCHOOL, JURONG WEST STREET 52,",
  "Sembawang Primary School Hall\n\n10 Sembawang Drive",
  "Sembawang Secondary School Field\n\n30 Sembawang Crescent",
  "Sembawang Secondary School Hall\n\n30 Sembawang Crescent",
  "Seng Kang Primary School Hall\n\n21, SENG KANG PRIMARY SCHOOL, COMPASSVALE WALK,",
  "Sengkang ActiveSG Gym\n\n57 Anchorvale Road",
  "Sengkang Green Primary School Field\n\n15 Fernvale Road",
  "Sengkang Hockey Pitch\n\n57 Anchorvale Road",
  "Sengkang Secondary School Field\n\n10 Compassvale Lane",
  "Sengkang Sport Centre\n\n57 Anchorvale Rd",
  "Sengkang Sports Hall\n\n57 Anchorvale Road",
  "Sengkang Swimming Complex\n\n57 Anchorvale Road",
  "Senja Cashew Gym\n\n101, BUKIT PANJANG ROAD,",
  "Senja-Cashew Swimming Complex\n\n101, BUKIT PANJANG ROAD,",
  "Senja-Cashew Tennis Centre\n\n101, SENJA-CASHEW COMMUNITY CLUB, BUKIT PANJANG ROAD,",
  "Serangoon Garden Secondary School Field\n\n21 Serangoon North Avenue 1",
  "Serangoon Garden Secondary School Hall\n\n21 Serangoon North Avenue 1",
  "Serangoon Secondary School Field\n\n11 Upper Serangoon View",
  "Serangoon Sport Centre\n\n35-A Yio Chu Kang Road",
  "Serangoon Stadium\n\n33 Yio Chu Kang Road",
  "Serangoon Swimming Complex\n\n35-A Yio Chu Kang Road",
  "Si Ling Primary School Hall\n\n61, SI LING PRIMARY SCHOOL, WOODLANDS AVENUE 1,",
  "Silver Circle ActiveSG Gym\n\n264 Serangoon Central #01-207",
  "South View Primary School\n\n6, CHOA CHU KANG CENTRAL Singapore 689762",
  "South View Primary School Field\n\n6 Choa Chu kang Central",
  "Spectra School Hall\n\n1 Woodlands Drive 64",
  "Springfield Secondary School Field\n\n30 Tampines Avenue 8",
  "St Gabriel's Secondary School Field\n\n24 Serangoon Avenue 1",
  "St Gabriel's Secondary School Hall\n\n24 Serangoon Avenue 1",
  "St Patrick's School Hall\n\n490, ST. PATRICKS SCHOOL, EAST COAST ROAD,",
  "St Wilfred Field\n\n3 St. Wilfred Road",
  "St Wilfred Squash Centre\n\n3 St. Wilfred Road",
  "St Wilfred Tennis Centre\n\n3 St. Wilfred Road",
  "Stamford Primary School Field\n\n1 Victoria Lane",
  "Stamford Primary School Hall\n\n1, STAMFORD PRIMARY SCHOOL, VICTORIA LANE,",
  "Tampines ActiveSG Gym\n\n1 Tampines Walk",
  "Tampines Meridian Junior College Field\n\n21 Pasir Ris Street 71",
  "Tampines North Primary School Hall\n\n30, TAMPINES NORTH PRIMARY SCHOOL, TAMPINES AVENUE 9,",
  "Tampines Secondary School Field\n\n252 Tampines Street 12",
  "Tampines Sport Centre\n\n1, OUR TAMPINES HUB, TAMPINES WALK,",
  "Tampines Swimming Complex\n\n1, OUR TAMPINES HUB, TAMPINES WALK,",
  "Tanglin Secondary School Field\n\n301 West Coast Road",
  "Tanjong Katong Secondary School Field\n\n130 Haig Road",
  "Teck Ghee Primary School Hall\n\n1, ANG MO KIO STREET 32,",
  "Temasek Primary School Field\n\n501 Bedok South Avenue 3",
  "Temasek Secondary School Field\n\n600 Upper East Coast Road",
  "Toa Payoh ActiveSG Gym\n\n301 Lorong 6 Toa Payoh",
  "Toa Payoh Petanque Courts\n\n297 Lorong 6 Toa Payoh",
  "Toa Payoh Sport Centre\n\n297A Lor 6 Toa Payoh",
  "Toa Payoh Sports Hall\n\n297 Lorong 6 Toa Payoh",
  "Toa Payoh Stadium\n\n297 Lorong 6 Toa Payoh",
  "Toa Payoh Swimming Complex\n\n301 Lorong 6 Toa Payoh",
  "Townsville Primary School Field\n\n3 Ang Mo Kio Avenue 10",
  "Unity Primary School Field\n\n21 Choa Chu Kang Crescent",
  "Unity Primary School Hall\n\n21 Choa Chu Kang Crescent",
  "Unity Secondary School Field\n\n20 Choa Chu Kang Street 62",
  "Unity Secondary School Hall\n\n20 Choa Chu Kang Street 62",
  "Waterway Primary School Field\n\n70 Punggol Drive",
  "West Grove Primary School Field\n\n1 Jurong West Street 72",
  "West Grove Primary School Hall\n\n1, WEST GROVE PRIMARY SCHOOL, JURONG WEST STREET 72,",
  "West Spring Secondary School Field\n\n61 Senja Road",
  "West Spring Secondary School Hall\n\n61 Senja Road",
  "West View Primary School Field\n\n31 Senja Road",
  "West View Primary School Hall\n\n31, WEST VIEW PRIMARY SCHOOL, SENJA ROAD,",
  "Westwood Primary School Hall\n\n1, WESTWOOD PRIMARY SCHOOL, JURONG WEST STREET 73,",
  "Westwood Secondary School Field\n\n11 Jurong West Street 25",
  "Westwood Secondary School Hall\n\n11, WESTWOOD SECONDARY SCHOOL, JURONG WEST STREET 25,",
  "White Sands Primary School Hall\n\n2, WHITE SANDS PRIMARY SCHOOL, PASIR RIS STREET 11,",
  "Woodgrove Primary School Hall\n\n2, WOODGROVE PRIMARY SCHOOL, WOODLANDS DRIVE 14,",
  "Woodgrove Secondary School Field\n\n3, WOODGROVE SECONDARY SCHOOL, WOODLANDS AVENUE 6,",
  "Woodgrove Secondary School Hall\n\n3, WOODGROVE SECONDARY SCHOOL, WOODLANDS AVENUE 6,",
  "Woodlands ActiveSG Gym\n\n3, WOODLANDS STREET 13",
  "Woodlands Primary School Field\n\n10 Woodlands Drive 50",
  "Woodlands Primary School Hall\n\n10, WOODLANDS PRIMARY SCHOOL, WOODLANDS DRIVE 50,",
  "Woodlands Ring Secondary School Field\n\n10 Woodlands Ring Road",
  "Woodlands Secondary School Field\n\n11 Marsiling Road",
  "Woodlands Secondary School Hall\n\n11 Marsiling Road",
  "Woodlands Sport Centre\n\n2, WOODLANDS STREET 13,",
  "Woodlands Sports Hall\n\n2 Woodlands St 12",
  "Woodlands Stadium\n\n1 Woodlands St 13",
  "Woodlands Swimming Complex\n\n3 Woodlands St 13",
  "Xing Hua Primary School\n\n45 Hougang Avenue 1",
  "Xingnan Primary School Field\n\n5 Jurong West Street 91",
  "Xinmin Secondary School Field\n\n11 Hougang Avenue 8",
  "Xishan Primary School Hall\n\n8, XISHAN PRIMARY SCHOOL, YISHUN STREET 21,",
  "Yew Tee Primary School Hall\n\n10, YEW TEE PRIMARY SCHOOL, CHOA CHU KANG STREET 64,",
  "Yio Chu Kang ActiveSG Gym\n\n200 Ang Mo Kio Avenue 9",
  "Yio Chu Kang Dance Studio\n\n214 Ang Mo Kio Avenue 9",
  "Yio Chu Kang Secondary School Field\n\n3063 Ang Mo Kio Avenue 5",
  "Yio Chu Kang Secondary School Hall\n\n3063 Ang Mo Kio Avenue 5",
  "Yio Chu Kang Sport Centre\n\n200, ANG MO KIO AVENUE 9,",
  "Yio Chu Kang Sports Hall\n\n200 Ang Mo Kio Avenue 9",
  "Yio Chu Kang Squash Centre\n\n200 Ang Mo Kio Avenue 9",
  "Yio Chu Kang Stadium\n\n210 Ang Mo Kio Avenue 9",
  "Yio Chu Kang Swimming Complex\n\n202 Ang Mo Kio Avenue 9",
  "Yio Chu Kang Tennis Centre\n\n200 Ang Mo Kio Avenue 9",
  "Yishun ActiveSG Gym\n\n101 Yishun Avenue 1",
  "Yishun Dance Studio\n\n101 Yishun Avenue 1",
  "Yishun Primary School Field",
  "Yishun Secondary School Hall\n\n4 Yishun Street 71",
  "Yishun Sport Centre\n\n101 Yishun Ave 1",
  "Yishun Sports Hall\n\n101 Yishun Avenue 1",
  "Yishun Stadium\n\n103 Yishun Avenue 1",
  "Yishun Swimming Complex\n\n351 Yishun Avenue 3",
  "Yishun Town Secondary School Hall\n\n6 Yishun Street 21",
  "Yuan Ching Secondary School Hall\n\n103 Yuan Ching Road",
  "Yuhua Primary School Field\n\n158 Jurong East Street 24 Singapore 609558",
  "Yuhua Secondary School Field\n\n35, YUHUA SECONDARY SCHOOL, JURONG WEST STREET 41,",
  "Yuhua Secondary School Hall\n\n35, YUHUA SECONDARY SCHOOL, JURONG WEST STREET 41,",
  "Yusof Ishak Secondary School Field\n\n11 Bukit Batok Street 25",
  "Yusof Ishak Secondary School Hall\n\n11 Bukit Batok Street 25",
  "Yuying Secondary School Hall\n\n47 Hougang Avenue 1",
  "Zhenghua Primary School Field\n\n9 Fajar Road",
  "Zhonghua Primary School Hall\n\n12 Serangoon Avenue 4",
];
export default facilities;
